
// Each new term in the Fibonacci sequence is generated by adding 
//the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values 
// do not exceed four million, find the sum of the even-valued terms.

document.write("Hello! This will calculate even sums based on the Fibonacci sequence.");
var limit = prompt("<br>Please enter a whole number limit.");
document.write("<br>Limit: " + limit);
var fibArray = [];
var a = 1, b = 1, n = 0;
fibArray.push(a);

while (b <= limit) {
    fibArray.push(b);
    n = b;
    b = a + b;
    a = n;  
}
document.write("<br>Full Fibonacci Sequence: " + fibArray);

var even_sum = 0;
for (var num = 0; num <= fibArray.length; ++num) {
  if ((fibArray[num]) % 2 == 0) {
    even_sum += fibArray[num];
  }
}

document.write("<br>Even sum: " + even_sum);
